### PR TITLE
conversations.getFromUser() conversation id fix

### LINKED ISSUE #3: conversations.getFromUser() doesn't work with the full cid as returned by conversations.create
the problem seems to be caused by this line:

https://github.com/layerhq/node-layer-api/blob/6519dd0dfa6f3264796a27228ff40e60a258ed56/lib/resources/conversations.js#L62

instead of
```javascript
conversationUUID ? '/' + conversationId : ''
```
it should be 
```javascript
conversationUUID ? '/' + conversationUUID : ''
```

### PR DESCRIPTION
**Pull request by adrian-gierakowski**
1. conversations.getFromUser() now works with full conversation id, fixes #3
2. added 2 options to layer-api constructor: 
  - agentOptions : creates a https.Agent specific to the created instance with  given options
  - agent : allows to pass a custom https.Agent instance so that it can be shared with other code. If `agent` option is provided `agentOptions` are ignored

### CODE REVIEW

File: lib/request.js [hunk 1]
```diff
@@ -57,23 +65,31 @@ function request(method, params, callback) {
...
   req.on('socket', function(socket) {
-    socket.on(('secureConnect'), function() {
+    var write = function() {
       if (params.body) req.write(JSON.stringify(params.body));
       req.end();
-    });
+    }
+    // reusing connection when using keepAlive agent
+    if (socket.authorized) write();
+    // TODO: should also check if authorized here and throw if not
```
Comment (nilgradisnik) [inline lib/request.js]: Technically this should never happen but we can add this check to be safe.

**Comment by nilgradisnik** [comment]
Great catch there on #3. Could you squash these 4 commits, then it's ready to merge.

**Comment by adrian-gierakowski** [comment]
@nilgradisnik : all squashed. I did not add the extra check for socket.authorized since I didn't know how you'd like to handle it if it returns false
